#!/bin/bash

### strict mode ###
set -euo pipefail
IFS=$'\n\t'

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
REMOTEHOME="$SCRIPTPATH/home/"
path_length=${#REMOTEHOME}

if [[ ! -d "$REMOTEHOME" ]]; then
   echo 'Error! Repository not correctly cloned!'
   exit 1
fi

confirm_action(){
   echo
   while true; do
      if [[ "$#" -ge 2 ]]; then
         if [[ "$2" == 'Y' || "$2" == 'y' ]]; then
            question="$1 [Y/n]: "
         elif [[ "$2" == 'N' || "$2" == 'n' ]]; then
            question="$1 [y/N]: "
         else
            question="$1 [y/n]: "
         fi
      else
         question="$1 [y/n]: "
      fi
      echo -en "$question"
      read -r answer
      if [[ "$#" -ge 2 && "$2" ]]; then
         answer=${answer:-"$2"}
      fi
      if [[ $answer = "Y" || $answer = "y" ]]; then
         return 0
         break
      elif [[ $answer = "n" ]]; then
         return 1
         break
      else
         echo "Invalid answer. Please, try again."
      fi
   done
}

if [[ -d ~/.git ]]; then
   echo 'Your home directory already contains a .git repository'
   echo 'This installer uses .git at home dir for the initial backup'
   echo 'which may later be used for uninstall.'
   echo
   echo 'If you want to continue, this repo must be removed'
   if confirm_action "Remove repo at home dir? (Caution!!!!!)?" "n"; then
      rm -rf ~/.git
   else
      exit 1
   fi
fi

cd ~
git init .

for file in $(find "$REMOTEHOME" -mindepth 1); do
   base="${file:$path_length}"
   if [[ -e "$HOME/$base" ]]; then
      git add "$HOME/$base"
   fi
done

git config user.email "user@email.com"
git config user.name "Username"
git config oh-my-zsh.hide-info 1

git commit -m "Backup"

for file in $(find "$REMOTEHOME" -mindepth 1); do
   base="${file:$path_length}"
   cp -r "$file" "$HOME/$base"
   git add "$HOME/$base"
done

git commit -m "Fresh install"

## make zsh as default shell
zshfile=$(which zsh)
if [[ -n "$zshfile" ]]; then
   sudo usermod -s "$zshfile" "$(whoami)"
fi

## download and install jetbrains fonts
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"

## download and install SF compact fonts
sudo mkdir -p /tmpfs/
sudo chmod 777 -R /tmpfs/
cd /tmpfs/
rm -rf /tmpfs/sf_compact
mkdir -p /tmpfs/sf_compact
wget -O /tmpfs/sf_compact/download.dmg "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg"
cd /tmpfs/sf_compact
7z x "/tmpfs/sf_compact/download.dmg"
7z x "/tmpfs/sf_compact/SFCompactFonts/SF Compact Fonts.pkg"
7z x "/tmpfs/sf_compact/Payload~"
mkdir -p ~/.local/share/fonts/fonts/San_Francisco
cp /tmpfs/sf_compact/Library/Fonts/SF-Compact-Display-Medium.otf \
~/.local/share/fonts/fonts/San_Francisco
cp /tmpfs/sf_compact/Library/Fonts/SF-Compact-Rounded-Medium.otf \
~/.local/share/fonts/fonts/San_Francisco
cp /tmpfs/sf_compact/Library/Fonts/SF-Compact-Text-Medium.otf \
~/.local/share/fonts/fonts/San_Francisco

## cleanup
rm -rf /tmpfs/sf_compact/
rm -rf /tmpfs/dotfiles/
