gui:
  theme:
    activeBorderColor:
      - '#cccccc'
      - bold
    inactiveBorderColor:
      - '#666'
  showFileTree: false
  commandLogSize: 16
  sidePanelWidth: 0.25
  nerdFontsVersion: "3"

promptToReturnFromSubprocess: false

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never

keybinding:
  universal:
    pushFiles: null
