gui:
  theme:
    activeBorderColor:
      - '#cccccc'
      - bold
    inactiveBorderColor:
      - '#666'
  showFileTree: false
  commandLogSize: 16
  sidePanelWidth: 0.3
  nerdFontsVersion: '3'
  scrollHeight: 20

promptToReturnFromSubprocess: false

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never

keybinding:
  universal:
    pushFiles: <disabled>
  commits:
    viewResetOptions: 'G'

customCommands:
  - key: 'P'
    context: 'commits'
    prompts:
      - type: 'menu'
        title: ''
        key: 'confirm'
        options:
          - name: 'git push (force)'
            description: 'up to selected commit'
            value: ''
    command: 'git push --force-with-lease origin {{.SelectedLocalCommit.Sha}}:{{.CheckedOutBranch.Name}}'
    loadingText: 'pushing up to selected commit ...'
